#!/usr/bin/env bash
REPO=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
set -uo pipefail
REPO=$REPO
ROOT=$(mktemp -d); export HOME=$ROOT
export XDG_STATE_HOME=$ROOT/state XDG_DATA_HOME=$ROOT/data XDG_RUNTIME_DIR=$ROOT/run
export HYPRCHROMA_LIB=$REPO/lib HYPRCHROMA_SHARE=$REPO/share
source "$(dirname "$0")/lib-omarchy.sh"
seed_omarchy_theme
mkdir -p "$XDG_RUNTIME_DIR"

S=$XDG_STATE_HOME/hyprchroma
mkdir -p "$S/original/files" "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0" "$HOME/.local/bin"
printf 'ORIGINAL-GTK3\n' > "$S/original/files/gtk3_css"
printf 'ORIGINAL-GTK4\n' > "$S/original/files/gtk4_css"
python3 - "$S/original/manifest.json" "$HOME" <<'E'
import json,sys
json.dump({"files":{
 "gtk3_css":{"path":f"{sys.argv[2]}/.config/gtk-3.0/gtk.css","existed":True,"backup":"files/gtk3_css"},
 "gtk4_css":{"path":f"{sys.argv[2]}/.config/gtk-4.0/gtk.css","existed":True,"backup":"files/gtk4_css"}},
 "gsettings":{}}, open(sys.argv[1],"w"))
E
sync() { bash "$REPO/bin/hyprchroma" "$@" 2>&1 | sed 's/^/    /'; }
# Two files now: the stylesheet this owns, and the user's gtk.css that only
# imports it. A revert must remove the first and hand back the second.
state() { head -1 "$HOME/.config/gtk-3.0/hyprchroma.css" 2>/dev/null || echo "(absent)"; }
usercss() { head -1 "$HOME/.config/gtk-3.0/gtk.css" 2>/dev/null || echo "(absent)"; }

echo "1. initial sync"; sync --force --quiet >/dev/null; echo "   gtk.css: $(state)"
echo "2. toggle OFF"; sync --target=gtk --set-enabled=false
echo "   ours: $(state)   user's: $(usercss)"
[[ $(state) == "(absent)" ]] && echo "   PASS our stylesheet removed" || echo "   FAIL stylesheet left behind"
[[ $(usercss) == "ORIGINAL-GTK3" ]] && echo "   PASS user's gtk.css handed back" || echo "   FAIL not reverted"
echo "3. toggle ON"; sync --target=gtk --set-enabled=true; echo "   gtk.css: $(state)"
[[ $(state) == *"Generated by Hyprchroma"* ]] && echo "   PASS refreshed" || echo "   FAIL not refreshed"
echo "4. toggle ON again (already on, unchanged theme)"; sync --target=gtk --set-enabled=true
echo "   gtk.css: $(state)"
[[ $(state) == *"Generated by Hyprchroma"* ]] && echo "   PASS still applied" || echo "   FAIL lost"
rm -rf "$ROOT"
