#!/usr/bin/env bash
# gtk.css belongs to the user. Taking it over meant their own rules there
# stopped applying the moment this was installed, and were overwritten again on
# every theme change. The colors live in a stylesheet of ours that gtk.css
# merely imports -- the approach Noctalia takes, and better than what was here.
REPO=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
cd -- "$REPO" || exit 1
chk(){ [[ $2 == "$3" ]] && echo "  PASS $1" || echo "  FAIL $1: got [$2] want [$3]"; }
code(){ sed -e 's/[[:space:]]*#.*//' "$@"; }
countcode(){ local pat=$1; shift; code "$@" | grep -ohE "$pat" | wc -l; }
L='@import url("hyprchroma.css");'
T=$(mktemp -d "$HOME/gtkimp-XXXXXX"); trap 'rm -rf "$T"' EXIT
st() { ./lib/hyprchroma-state "$@"; }

# --- the user's file is added to, never replaced ---------------------------
printf '/* MINE */\nwindow { opacity: 0.9; }\n' > "$T/gtk.css"
chk "an existing file is added to" "$(st ensure-import --path "$T/gtk.css" --line "$L")" "added"
chk "the user's content is still there" "$(grep -c 'MINE' "$T/gtk.css")" "1"
# Later @define-color wins in GTK, so appending would silently override the
# user. First means ours are defaults and theirs take precedence.
chk "the import goes first, so the user can override" "$(head -1 "$T/gtk.css")" "$L"
chk "running again changes nothing" "$(st ensure-import --path "$T/gtk.css" --line "$L")" "present"

# --- removal gives the file back -------------------------------------------
chk "removal strips only our line" "$(st remove-import --path "$T/gtk.css" --line "$L")" "stripped"
chk "the user's content survived removal" "$(grep -c 'MINE' "$T/gtk.css")" "1"
chk "our line is gone" "$(grep -c 'hyprchroma.css' "$T/gtk.css")" "0"

# --- a file that was only ever ours is removed outright --------------------
rm -f "$T/gtk.css"
st ensure-import --path "$T/gtk.css" --line "$L" >/dev/null
chk "a file created for the import is deleted with it" \
  "$(st remove-import --path "$T/gtk.css" --line "$L")" "removed"
chk "and it really is gone" "$([ -e "$T/gtk.css" ] && echo there || echo gone)" "gone"

# --- upgrading from the version that owned gtk.css -------------------------
printf '/* Generated by Hyprchroma from the active Omarchy palette. */\n@define-color x #111;\n' > "$T/gtk.css"
chk "a whole file written by an older version is replaced" \
  "$(st ensure-import --path "$T/gtk.css" --line "$L")" "migrated"
chk "nothing of that old file is kept" "$(wc -l < "$T/gtk.css")" "1"

# --- a backup must never carry our output ----------------------------------
chk "the probe sees the import" "$(countcode 'HYPRCHROMA_IMPORT in text' lib/hyprchroma-state)" "1"
# Three: the pre-existing whole-file probe, plus the gtk.css probe and cleaner.
chk "the probe also sees a legacy whole file" \
  "$(countcode 'GENERATED_MARKER in text' lib/hyprchroma-state)" "3"
chk "gtk.css is cleaned before it is backed up" \
  "$(countcode '"gtk3_css": strip_hyprchroma_import' lib/hyprchroma-state)" "1"
chk "gtk.css is no longer treated as wholly ours" \
  "$(countcode 'WHOLLY_GENERATED = frozenset\(\{"hyprchroma_colors", "pear_css",' lib/hyprchroma-state)" "1"
chk "the stylesheet we own is" \
  "$(countcode 'gtk3_hyprchroma_css' lib/hyprchroma-state)" "4"

# --- both restore paths take the import back out ---------------------------
chk "captured and stock restores both strip it" \
  "$(countcode 'remove_import\(Path.home\(\)' lib/hyprchroma-state)" "2"

# --- setting a theme that is not installed looks like a failure ------------
chk "the GTK theme is checked before it is set" \
  "$(countcode 'gtk_theme_installed "\$gtk_theme"' lib/sync-gtk-theme)" "1"
chk "it looks where GTK actually looks" \
  "$(countcode '/usr/share/themes' lib/sync-gtk-theme)" "1"
chk "a missing theme is said out loud" \
  "$(grep -c 'is not installed; GTK 3 apps will not follow' lib/sync-gtk-theme)" "1"

# --- gsettings is not the only way to write those keys ---------------------
chk "there is a dconf fallback" "$(countcode 'dconf write' lib/sync-gtk-theme)" "1"
# gtk-theme, color-scheme, accent-color, icon-theme, monospace-font-name.
chk "every interface key goes through it" \
  "$(countcode 'set_interface [a-z-]+' lib/sync-gtk-theme)" "5"
# One remains, inside set_interface itself: that is the implementation.
chk "only set_interface writes an interface key" \
  "$(countcode 'gsettings set org.gnome.desktop.interface ' lib/sync-gtk-theme)" "1"
