#!/usr/bin/env bash
REPO=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
set -uo pipefail
REPO=$REPO
ROOT=$(mktemp -d); export HOME=$ROOT
STUB=$ROOT/stub; mkdir -p "$STUB"
printf '#!/usr/bin/env bash\necho "%s"\n' "'val'" > "$STUB/gsettings"; chmod +x "$STUB/gsettings"
export PATH="$STUB:$PATH"
S=$ROOT/.local/state/hyprchroma; D=$ROOT/.local/share/hyprchroma
mkdir -p "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0" \
         "$HOME/.local/share/color-schemes" "$HOME/.config/YouTube Music"
snap() { python3 "$REPO/lib/hyprchroma-state" --state-dir "$S" --data-dir "$D" snapshot --target "$1"; }
q() { python3 -c "import json;m=json.load(open('$S/original/manifest.json'));print($1)"; }
chk(){ [[ $2 == "$3" ]] && echo "  PASS $1" || echo "  FAIL $1: got [$2] want [$3]"; }

echo "--- state dir lost, Hyprchroma output still on disk ---"
printf '/* Generated by Hyprchroma from the active Omarchy palette. */\nbody{}\n' > "$HOME/.config/gtk-3.0/gtk.css"
printf 'REAL-USER-GTK4\n' > "$HOME/.config/gtk-4.0/gtk.css"
printf '[General]\nColorScheme=Hyprchroma\n[Shortcuts]\nmine=Ctrl+X\n' > "$HOME/.config/kdeglobals"
printf 'OURS\n' > "$HOME/.local/share/color-schemes/Hyprchroma.colors"
printf 'OURS\n' > "$HOME/.config/YouTube Music/hyprchroma.css"
printf '{\n\t"url": "REAL",\n\t"options": {"themes": ["/u/mine.css", "%s/.config/YouTube Music/hyprchroma.css"]}\n}\n' "$HOME" > "$HOME/.config/YouTube Music/config.json"
snap gtk; snap qt-kde; snap pear

chk "generated gtk3 flagged"        "$(q 'm["files"]["gtk3_css"].get("generated")')" "True"
chk "genuine gtk4 NOT flagged"      "$(q 'm["files"]["gtk4_css"].get("generated")')" "None"
chk "genuine gtk4 still backed up"  "$(cat "$S/original/files/gtk4_css")" "REAL-USER-GTK4"
chk "kdeglobals flagged but kept"   "$(q '(m["files"]["kdeglobals"].get("generated"), m["files"]["kdeglobals"]["existed"])')" "(True, True)"
chk "Hyprchroma.colors -> absent"   "$(q 'm["files"]["hyprchroma_colors"]["existed"]')" "False"
chk "pear css -> absent"            "$(q 'm["files"]["pear_css"]["existed"]')" "False"
chk "manifest marked tainted"       "$(q 'm.get("captureTainted")')" "True"
chk "generated gtk3 -> recorded absent" "$(q 'm["files"]["gtk3_css"]["existed"]')" "False"
chk "generated gtk3 -> no backup"       "$(q 'm["files"]["gtk3_css"].get("backup")')" "None"
chk "kdeglobals backup keeps user data" "$(grep -c 'mine=Ctrl+X' "$S/original/files/kdeglobals")" "1"
chk "kdeglobals backup is CLEAN"        "$(grep -c 'Hyprchroma' "$S/original/files/kdeglobals")" "0"
echo "  -- invariant: no backup file may contain Hyprchroma output --"
bad=$(grep -rl 'Hyprchroma' "$S/original/files/" 2>/dev/null | wc -l)
chk "no backup contains Hyprchroma"     "$bad" "0"
chk "pear backup stripped of ours"  "$(python3 -c "import json;print(json.load(open('$S/original/files/pear_config'))['options']['themes'])")" "['/u/mine.css']"
chk "pear backup keeps real url"    "$(python3 -c "import json;print(json.load(open('$S/original/files/pear_config'))['url'])")" "REAL"

echo "--- clean machine: nothing flagged ---"
R2=$(mktemp -d); export HOME=$R2; S=$R2/.local/state/hyprchroma
mkdir -p "$HOME/.config/gtk-3.0"; printf 'REAL\n' > "$HOME/.config/gtk-3.0/gtk.css"
snap gtk
chk "clean capture untainted" "$(q 'm.get("captureTainted")')" "None"
chk "clean gtk3 backed up"    "$(cat "$S/original/files/gtk3_css")" "REAL"
rm -rf "$ROOT" "$R2"
